version: '3.8'

services:
  proxy-back:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  back:
    environment:
      - UseDebugEmailSender=false
      - ConnectionStrings__POSTGRES=${ITLAB_USERS_AND_EVENTS_DB?Place users and events db connection string}
      - DocsGeneratorSettings__AccessToken=${ITLAB_DOCS_GEN_TOKEN?Place docs gen access token}
      - EmailSenderOptions__BaseAddress=${ITLAB_EMAIL_SENDER_BASE_ADDRESS?Place email sender base address}
      - EmailSenderOptions__Key=${ITLAB_EMAIL_SENDER_ACCESS_KEY?Place email sender api key ITLAB_EMAIL_SENDER_ACCESS_KEY}
      - Authority=${ITLAB_IDENTITY_ISSUER?Place identity issuer}
      - EmailTemplateSettings__InvitationTemplateUrl=${ITLAB_EMAIL_TEMPLATE_INVITATION_URL?Place email invitation template url ITLAB_EMAIL_TEMPLATE_INVITATION_URL}
      - EmailTemplateSettings__ResetPasswordTemplateUrl=${ITLAB_EMAIL_TEMPLATE_RESET_PASSWORD_URL?Place email reset password template url ITLAB_EMAIL_TEMPLATE_RESET_PASSWORD_URL}
      - DB_TYPE=POSTGRES
      - DB_INIT=false
      - AuthHeaderSettings__Key=${ITLAB_NOTIFY_AUTH_TOKEN?Provide notify get all users token from ITLab-Back ITLAB_NOTIFY_AUTH_TOKEN}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  docsgen:
    environment:
      - Url=http://back:5503
      - Key=${ITLAB_DOCS_GEN_TOKEN?Place docs gen access token}
      - Header=Authorization
      - IssuerUrl=${ITLAB_IDENTITY_ISSUER?Place identity issuer}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  projects-back:
    environment:
      # auth
      - ITLABPROJ_KEYURL=${ITLAB_IDENTITY_JWKSIURL?Place identity issuer ITLAB_IDENTITY_JWKSIURL}
      - ITLABPROJ_AUDIENCE=itlab
      - ITLABPROJ_ISSUER=${ITLAB_IDENTITY_ISSUER?Place identity issuer}
      - ITLABPROJ_SCOPE=itlab.projects
      # db
      - ITLABPROJ_URI=${ITLAB_PROJECTS_MONGO_DB?Place mongo connection string for projects service ITLAB_PROJECTS_MONGO_DB}
      # app
      - ITLABPROJ_APPPORT=5505
      - ITLABPROJ_TESTMODE=false
      - ITLABPROJ_PROJFILEBRANCH=master
      - ITLABPROJ_ELEMSPERPAGE=40
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  reports-back:
    environment:
    # db
    - ITLAB_REPORTS_MONGO_URI=${ITLAB_REPORTS_MONGO_DB?Place mongo connection string for reports service ITLAB_REPORTS_MONGO_DB}

    # auth
    - ITLAB_REPORTS_AUTH_KEY_URL=${ITLAB_IDENTITY_JWKSIURL?Place identity issuer ITLAB_IDENTITY_JWKSIURL}
    - ITLAB_REPORTS_AUTH_ISSUER=${ITLAB_IDENTITY_ISSUER?Place identity issuer ITLAB_IDENTITY_ISSUER}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  mfs:
    environment:
    # db
    - MFS_MONGO_URI=${ITLAB_MFS_MONGO_DB?Place mongo connection string for mfs service ITLAB_MFS_MONGO_DB}

    # auth
    - MFS_AUTH_KEY_URL=${ITLAB_IDENTITY_JWKSIURL?Place identity issuer ITLAB_IDENTITY_JWKSIURL}
    - MFS_AUTH_ISSUER=${ITLAB_IDENTITY_ISSUER?Place identity issuer ITLAB_IDENTITY_ISSUER}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  salary: 
    environment:
    - ConnectionStrings__MongoDb=${ITLAB_SALARY_MONGO_DB?Place mondo db connection string ITLAB_SALARY_MONGO_DB}
    - JwtOptions__Authority=${ITLAB_IDENTITY_ISSUER?Place identity issuer ITLAB_IDENTITY_ISSUER}
    - RemoteApiEventsServiceOptions__ClientSecret=${ITLAB_SALARY_CLIENT_SECRET?Place salary client secret ITLAB_SALARY_CLIENT_SECRET}
    - RemoteApiEventsServiceOptions__TokenUrl=${ITLAB_IDENTITY_ISSUER?Place identity issuer ITLAB_IDENTITY_ISSUER}/connect/token
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  feedback:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5509
      - POSTGRES=${ITLAB_FEEDBACK_DB?Provide postgres connection string in ITLAB_FEEDBACK_DB}
      - IdentityURL=${ITLAB_IDENTITY_ISSUER?Provide identity url ITLAB_IDENTITY_ISSUER}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  notify:
    environment:
      - ITLAB_NOTIFY_PORT=5511
      - ITLAB_NOTIFY_REDIS_HOST=${ITLAB_NOTIFY_REDIS_HOST?Provide redis host in ITLAB_NOTIFY_REDIS_HOST}
      - ITLAB_NOTIFY_REDIS_PORT=${ITLAB_NOTIFY_REDIS_PORT?Provide redis port in ITLAB_NOTIFY_REDIS_PORT}
      - ITLAB_NOTIFY_REDIS_PASSWORD=${ITLAB_NOTIFY_REDIS_PASSWORD?Provide redis password in ITLAB_NOTIFY_REDIS_PASSWORD}
      - ITLAB_NOTIFY_DB_HOST=${ITLAB_NOTIFY_DB_HOST?Provide notify postgres database host in ITLAB_NOTIFY_DB_HOST}
      - ITLAB_NOTIFY_DB_PORT=${ITLAB_NOTIFY_DB_PORT?Provide notify postgres database port in ITLAB_NOTIFY_DB_PORT}
      - ITLAB_NOTIFY_DB_NAME=${ITLAB_NOTIFY_DB_NAME?Provide notify postgres database name in ITLAB_NOTIFY_DB_NAME}
      - ITLAB_NOTIFY_DB_USER=${ITLAB_NOTIFY_DB_USER?Provide notify postgres database username in ITLAB_NOTIFY_DB_USER}
      - ITLAB_NOTIFY_DB_PASS=${ITLAB_NOTIFY_DB_PASS?Provide notify postgres database password in ITLAB_NOTIFY_DB_PASS}
      - ITLAB_NOTIFY_AUTH_URL=${ITLAB_NOTIFY_AUTH_URL?Provide notify get all users url from ITLab-Back ITLAB_NOTIFY_AUTH_URL}
      - ITLAB_NOTIFY_AUTH_TOKEN=${ITLAB_NOTIFY_AUTH_TOKEN?Provide notify get all users token from ITLab-Back ITLAB_NOTIFY_AUTH_TOKEN}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"