version: '3.8'

services:
  proxy-back:
    image: rtuitlab/itlab-proxy-back
  back:
    image: rtuitlab/itlab-back
  docsgen:
    image: rtuitlab/itlab-docsgen
  projects-back:
    image: rtuitlab/itlab-projects-back
    environment:
    - ITLABPROJ_GHACCESSTOKEN=${ITLABPROJ_GH_ACCESS_TOKEN?Place GitHub access token for projects-back in ITLABPROJ_GH_ACCESS_TOKEN}
    # app
    - ITLABPROJ_APPPORT=5505
    # auth
    - ITLABPROJ_AUDIENCE=itlab
    - ITLABPROJ_SCOPE=itlab.projects


  reports-back:
    image: rtuitlab/itlab-reports-back
    environment:
    # app
    - ITLAB_REPORTS_APP_PORT=5506
    - ITLAB_REPORTS_APP_TEST_MODE=false
    # auth
    - ITLAB_REPORTS_AUTH_SCOPE=itlab.reports
    - ITLAB_REPORTS_AUTH_AUDIENCE=itlab
  mfs:
    image: rtuitlab/mfs
    environment:
    # app
    - MFS_APP_PORT=5507
    - MFS_APP_TEST_MODE=false
    - MFS_APP_MFS_APP_MAX_FILE_SIZE=100
    - MFS_APP_PATH_PREFIX=/api/mfs
    # auth
    - MFS_AUTH_AUDIENCE=itlab
  salary:
    image: rtuitlab/salary
    environment:
    - JwtOptions__Audience=itlab
    - TESTS=false
    - EventsServiceType=FromEventsApi
    - RemoteApiEventsServiceOptions__BaseUrl=http://proxy:5500/api/event/




