version: '3.8'

services:
  proxy-back:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  back:
    environment:
      - UseDebugEmailSender=false
      - ConnectionStrings__POSTGRES=${ITLAB_USERS_AND_EVENTS_DB?Place users and events db connection string}
      - DocsGeneratorSettings__AccessToken=${ITLAB_DOCS_GEN_TOKEN?Place docs gen access token}
      - EmailSenderOptions__BaseAddress=${ITLAB_EMAIL_SENDER_BASE_ADDRESS?Place email sender base address}
      - EmailSenderOptions__Key=${ITLAB_EMAIL_SENDER_ACCESS_KEY?Place email sender api key ITLAB_EMAIL_SENDER_ACCESS_KEY}
      - Authority=${ITLAB_IDENTITY_ISSUER?Place identity issuer}
      - EmailTemplateSettings__InvitationTemplateUrl=${ITLAB_EMAIL_TEMPLATE_INVITATION_URL?Place email invitation template url ITLAB_EMAIL_TEMPLATE_INVITATION_URL}
      - EmailTemplateSettings__ResetPasswordTemplateUrl=${ITLAB_EMAIL_TEMPLATE_RESET_PASSWORD_URL?Place email reset password template url ITLAB_EMAIL_TEMPLATE_RESET_PASSWORD_URL}
      - DB_TYPE=POSTGRES
      - DB_INIT=false
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  docsgen:
    environment:
      - Url=http://back:5503
      - Key=${ITLAB_DOCS_GEN_TOKEN?Place docs gen access token}
      - Header=Authorization
      - IssuerUrl=${ITLAB_IDENTITY_ISSUER?Place identity issuer}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  projects-back:
    environment:
      # auth
      - ITLABPROJ_KEYURL=${ITLAB_IDENTITY_JWKSIURL?Place identity issuer ITLAB_IDENTITY_JWKSIURL}
      - ITLABPROJ_AUDIENCE=itlab
      - ITLABPROJ_ISSUER=${ITLAB_IDENTITY_ISSUER?Place identity issuer}
      - ITLABPROJ_SCOPE=itlab.projects
      # db
      - ITLABPROJ_URI=${ITLAB_PROJECTS_MONGO_DB?Place mongo connection string for projects service ITLAB_PROJECTS_MONGO_DB}
      # app
      - ITLABPROJ_APPPORT=5505
      - ITLABPROJ_TESTMODE=false
      - ITLABPROJ_PROJFILEBRANCH=master
      - ITLABPROJ_ELEMSPERPAGE=40
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  reports-back:
    environment:
    # db
    - ITLAB_REPORTS_MONGO_URI=${ITLAB_REPORTS_MONGO_DB?Place mongo connection string for reports service ITLAB_REPORTS_MONGO_DB}

    # auth
    - ITLAB_REPORTS_AUTH_KEY_URL=${ITLAB_IDENTITY_JWKSIURL?Place identity issuer ITLAB_IDENTITY_JWKSIURL}
    - ITLAB_REPORTS_AUTH_ISSUER=${ITLAB_IDENTITY_ISSUER?Place identity issuer ITLAB_IDENTITY_ISSUER}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  mfs:
    environment:
    # db
    - MFS_MONGO_URI=${ITLAB_MFS_MONGO_DB?Place mongo connection string for mfs service ITLAB_MFS_MONGO_DB}

    # auth
    - MFS_AUTH_KEY_URL=${ITLAB_IDENTITY_JWKSIURL?Place identity issuer ITLAB_IDENTITY_JWKSIURL}
    - MFS_AUTH_ISSUER=${ITLAB_IDENTITY_ISSUER?Place identity issuer ITLAB_IDENTITY_ISSUER}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  salary: 
    environment:
    - ConnectionStrings__MongoDb=${ITLAB_SALARY_MONGO_DB?Place mondo db connection string ITLAB_SALARY_MONGO_DB}
    - JwtOptions__Authority=${ITLAB_IDENTITY_ISSUER?Place identity issuer ITLAB_IDENTITY_ISSUER}
    - RemoteApiEventsServiceOptions__ClientSecret=${ITLAB_SALARY_CLIENT_SECRET?Place salary client secret ITLAB_SALARY_CLIENT_SECRET}
    - RemoteApiEventsServiceOptions__TokenUrl=${ITLAB_IDENTITY_ISSUER?Place identity issuer ITLAB_IDENTITY_ISSUER}/connect/token
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"