version: '3.8'

services:
  proxy-back:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  back:
    environment:
      - UseDebugEmailSender=false
      - ConnectionStrings__POSTGRES=${ITLAB_USERS_AND_EVENTS_DB?Place users and events db connection string}
      - DocsGeneratorSettings__AccessToken=${ITLAB_DOCS_GEN_TOKEN?Place docs gen access token}
      - EmailSenderOptions__BaseAddress=${ITLAB_EMAIL_SENDER_BASE_ADDRESS?Place email sender base address}
      - EmailSenderOptions__Key=${ITLAB_EMAIL_SENDER_ACCESS_KEY?Place email sender api key ITLAB_EMAIL_SENDER_ACCESS_KEY}
      - Authority=${ITLAB_IDENTITY_ISSUER?Place identity issuer}
      - DB_TYPE=POSTGRES
      - DB_INIT=false
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  docsgen:
    environment:
      - Url=http://back:5503
      - Key=${ITLAB_DOCS_GEN_TOKEN?Place docs gen access token}
      - Header=Authorization
      - IssuerUrl=${ITLAB_IDENTITY_ISSUER?Place identity issuer}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  projects-back:
    environment:
      # auth
      - ITLABPROJ_KEYURL=${ITLAB_IDENTITY_JWKSIURL?Place identity issuer ITLAB_IDENTITY_JWKSIURL}
      - ITLABPROJ_AUDIENCE=itlab
      - ITLABPROJ_ISSUER=${ITLAB_IDENTITY_ISSUER?Place identity issuer}
      - ITLABPROJ_SCOPE=itlab.projects
      # db
      - ITLABPROJ_HOST=${ITLAB_PROJECTS_MONGO_HOST?Place mongo host for projects service}
      - ITLABPROJ_DBPORT=27017
      - ITLABPROJ_DBNAME=${ITLAB_PROJECTS_MONGO_DB?Place mongo db name for projects service}
      - ITLABPROJ_PROJCOLNAME=projects
      - ITLABPROJ_LABSCOLNAME=labels
      - ITLABPROJ_ISSSCOLNAME=issues
      # app
      - ITLABPROJ_APPPORT=5505
      - ITLABPROJ_TESTMODE=false
      - ITLABPROJ_PROJFILEBRANCH=master
      - ITLABPROJ_ELEMSPERPAGE=40
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  reports-back:
    environment:
    # db
    - ITLAB_REPORTS_MONGO_HOST=${ITLAB_PROJECTS_MONGO_HOST?Place mongo host for projects service ITLAB_PROJECTS_MONGO_HOST}
    - ITLAB_REPORTS_MONGO_PORT=27017
    - ITLAB_REPORTS_MONGO_DB_NAME=${ITLAB_PROJECTS_MONGO_DB?Place mongo db name for projects service ITLAB_PROJECTS_MONGO_DB}
    - ITLAB_REPORTS_MONGO_DB_COLLECTION_NAME=reports

    # auth
    - ITLAB_REPORTS_AUTH_KEY_URL=${ITLAB_IDENTITY_JWKSIURL?Place identity issuer ITLAB_IDENTITY_JWKSIURL}
    - ITLAB_REPORTS_AUTH_ISSUER=${ITLAB_IDENTITY_ISSUER?Place identity issuer ITLAB_IDENTITY_ISSUER}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  mfs:
    environment:
    # db
    - MFS_MONGO_HOST=${ITLAB_PROJECTS_MONGO_HOST?Place mongo host for projects service ITLAB_PROJECTS_MONGO_HOST}
    - MFS_MONGO_PORT=27017
    - MFS_MONGO_DB_NAME=${ITLAB_MFS_MONGO_DB?Place mongo db name for projects service ITLAB_MFS_MONGO_DB}
    - MFS_MONGO_DB_COLLECTION_NAME=fs.files

    # auth
    - MFS_AUTH_KEY_URL=${ITLAB_IDENTITY_JWKSIURL?Place identity issuer ITLAB_IDENTITY_JWKSIURL}
    - MFS_AUTH_ISSUER=${ITLAB_IDENTITY_ISSUER?Place identity issuer ITLAB_IDENTITY_ISSUER}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  salary: 
    environment:
    - ConnectionStrings__MongoDb=${ITLAB_SALARY_MONGO_DB?Place mondo db connection string ITLAB_SALARY_MONGO_DB}
    - JwtOptions__Authority=${ITLAB_IDENTITY_ISSUER?Place identity issuer ITLAB_IDENTITY_ISSUER}
    - RemoteApiEventsServiceOptions__ClientSecret=${ITLAB_SALARY_CLIENT_SECRET?Place salary client secret ITLAB_SALARY_CLIENT_SECRET}
    - RemoteApiEventsServiceOptions__TokenUrl=${ITLAB_IDENTITY_ISSUER?Place identity issuer ITLAB_IDENTITY_ISSUER}/connect/token
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"