version: '3.8'

services:
  proxy-back:
    build: Proxy-Back
    ports:
      - 5501:5501
      - 5502:5502
      - 5503:5503
    restart: on-failure
  identity:
    build: ITLab-Identity/deploy/identity
    restart: on-failure
    environment:
      - ConnectionStrings__ConfigurationDbConnection=User ID=postgres;Password=password;Server=postgres;Port=5432;Database=itlab-identity-dev-db;Integrated Security=true;
      - ConnectionStrings__PersistedGrantDbConnection=User ID=postgres;Password=password;Server=postgres;Port=5432;Database=itlab-identity-dev-db;Integrated Security=true;
      - ConnectionStrings__IdentityDbConnection=User ID=postgres;Password=password;Server=postgres;Port=5432;Database=itlab-back-dev-db;Integrated Security=true;
  identity-admin:
    build: ITLab-Identity/deploy/admin
    restart: on-failure
    environment:
      - ConnectionStrings__ConfigurationDbConnection=User ID=postgres;Password=password;Server=postgres;Port=5432;Database=itlab-identity-dev-db;Integrated Security=true;
      - ConnectionStrings__PersistedGrantDbConnection=User ID=postgres;Password=password;Server=postgres;Port=5432;Database=itlab-identity-dev-db;Integrated Security=true;
      - ConnectionStrings__IdentityDbConnection=User ID=postgres;Password=password;Server=postgres;Port=5432;Database=itlab-back-dev-db;Integrated Security=true;
      - ConnectionStrings__AdminLogDbConnection=User ID=postgres;Password=password;Server=postgres;Port=5432;Database=itlab-identity-dev-db;Integrated Security=true;
      - ConnectionStrings__AdminAuditLogDbConnection=User ID=postgres;Password=password;Server=postgres;Port=5432;Database=itlab-identity-dev-db;Integrated Security=true;
  back:
    build: ITLab-Back/deploy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - UseDebugEmailSender=true
      - ConnectionStrings__POSTGRES=User ID=postgres;Password=password;Server=postgres;Port=5432;Database=itlab-back-dev-db;Integrated Security=true;

  postgres:
    image: postgres:13-alpine
    environment:
        - POSTGRES_PASSWORD=password
    ports:
        - 5432:5432
    restart: on-failure
    logging:
        driver: "json-file"
        options:
            max-size: "200k"
            max-file: "10"